### ISSUE TITLE
Incomplete prtList with delimiters

### ISSUE THREAD

**Issue by gdetrez** [BNFC/bnfc#106]
With the following example:

```
S. S ::= "#" [A] ;
A. A ::= "a" ;
delimiters A "[" "]"  separator "," ;
```

```
$ bnfc --haskell --cnf -m test.cf && make
$ echo "# [ a ]" | ./TestCNF
```

You get `TestCNF: Printtest.hs:(92,16)-(93,64): Non-exhaustive patterns in case` because the following doesn't have a case for a non empty list:

``` haskell
 prtList es = case es of
   [] -> (concatD [doc (showString "[") , doc (showString "]")])
```

**Comment by andreasabel** [comment]
The `delimiters` pragma has been removed in 2.9.0.
