### ISSUE TITLE
Problems with C and `entrypoints`

### ISSUE THREAD

**Issue by gdetrez** [BNFC/bnfc#127]
It seems that the generated C parser doesn't like it when using an entry point which is not the first category:
```
entrypoints Bar;
F. Foo ::= "foo" ;
B. Bar ::= "bar" ;
```

```
$ bnfc -c -m Test.cf && make
...
$ ./TestTest <<< foo
$ ./TestTest <<< bar
error: syntax error
```

It looks like `foo` is parsed but nothing is printed but `bar`, which should be the correct one in that case, is not parsed. It works fine if one removes the `entrypoints` pragma:
```
$  ./TestTest <<< bar

Parse Succesful!

[Abstract Syntax]
B

[Linearized Tree]
bar 
```

**Comment by sirdude** [comment]
cpp has the same issue...  Should probably check the others too.
