### ISSUE TITLE
Pretty-printer chokes on category named `I`

### ISSUE THREAD

**Issue by danr** [BNFC/bnfc#134]
With this grammar:

    Foo. S ::= I ;
    Bar. I ::= "i" ;

this error is obtained:    

    $ bnfc I.cf -m && make 
    ...
    happy -gca ParI.y
    alex -g LexI.x
    ghc --make TestI.hs -o TestI
    [3 of 7] Compiling PrintI           ( PrintI.hs, PrintI.o )

    PrintI.hs:85:20:
        Couldn't match expected type ‘Int’ with actual type ‘I’
        In the first argument of ‘prPrec’, namely ‘i’
        In the expression: prPrec i 0 (concatD [prt 0 i])
    Makefile:2: recipe for target 'all' failed
    make: *** [all] Error 1

**Comment by andreasabel** [comment]
Now tested along with #278.
