### ISSUE TITLE
BNFC-meta documentation doesn't build

### ISSUE THREAD

**Issue by woehr** [BNFC/bnfc#136]
I apologize if this isn't the right place for BNFC-meta issues. I couldn't find its repo.

BNFC-meta's documentation doesn't build with the following error:

```
HsColour: Language/LBNF/CFtoHappy.hs: hGetContents: invalid argument (invalid byte sequence)
```

**Comment by gdetrez** [comment]
BNFC meta is not really part of BNFC and I don't know if they have a public repository. I suggest you contact Jonas about this problem (his email is on the hackage page for [BNFC-meta](https://hackage.haskell.org/package/BNFC-meta))
