### ISSUE TITLE
BNFC-2.7.1. does not compile with GHC 7.10.1

### ISSUE THREAD

**Issue by peti** [BNFC/bnfc#137]
There's a whole bunch of errors that look like they might be trivial to fix (i.e. by adding the FlexibleContexts extension). A complete build log that shows all errors is available at http://hydra.cryp.to/build/727140/nixlog/1/raw.

**Comment by gdetrez** [comment]
I just merged a pull request that should fix this

**Comment by peti** [comment]
Will you release a new version to Hackage?

**Comment by gdetrez** [comment]
Good idea, I'll try to do it this month.
