### ISSUE TITLE
bnfc gives unhelpful error messages

### ISSUE THREAD

**Issue by danr** [BNFC/bnfc#144]
On this grammar:

    Test.  Test ::= " ")";

bnfc reports:

    bnfc: src/LexBNF.x:(80,13)-(86,20): Non-exhaustive patterns in case

The error message could be more helpful! :)

**Comment by gdetrez** [comment]
is this better?

    bnfc: syntax error at line 1, column 20 before `)'

**Comment by danr** [comment]
Definitely!
