### ISSUE TITLE
Latest github release (bnfc-2.8) for linux are empty

### ISSUE THREAD

**Issue by bezirg** [BNFC/bnfc#147]
The latest github release tar.gz package for linux 32 bit and 64 bit 
contains only the LICENSE inside.

Check:

<https://github.com/BNFC/bnfc/releases/download/v2.8/BNFC-2.8-linux32.tar.gz>
and
<https://github.com/BNFC/bnfc/releases/download/v2.8/BNFC-2.8-linux64.tar.gz>

**Comment by gdetrez** [comment]
HI. Thanks for the bug report. I'm not completely sure how you get this. I get one executable but no LICENSE file (which should probably be included actually...):

```shell
~/tmp ❯❯❯ wget  https://github.com/BNFC/bnfc/releases/download/v2.8/BNFC-2.8-linux64.tar.gz
~/tmp ❯❯❯ tar xf BNFC-2.8-linux64.tar.gz
~/tmp ❯❯❯ ls -l
total 56
-rwxr-xr-x 1 gregoire gregoire 18009 May  8 18:46 BNFC-2.8-linux64
-rw-rw-r-- 1 gregoire gregoire  6986 May  8 18:51 BNFC-2.8-linux64.tar.gz
```

**Comment by bezirg** [comment]
try:

> file BNFC-2.8-linux64
On 1 Jul 2015 17:37, bezirg@gmail.com wrote:

That file extracted is the license, not an executable
On 1 Jul 2015 16:41, "Grégoire Détrez" <notifications@github.com> wrote:

HI. Thanks for the bug report. I'm not completely sure how you get this. I
get one executable but no LICENSE file (which should probably be included
actually...):

~/tmp ❯❯❯ wget
https://github.com/BNFC/bnfc/releases/download/v2.8/BNFC-2.8-linux64.tar.gz~/tmp
❯❯❯ tar xf BNFC-2.8-linux64.tar.gz~/tmp ❯❯❯ ls -l
total 56
-rwxr-xr-x 1 gregoire gregoire 18009 May  8 18:46 BNFC-2.8-linux64
-rw-rw-r-- 1 gregoire gregoire  6986 May  8 18:51 BNFC-2.8-linux64.tar.gz

—
Reply to this email directly or view it on GitHub
<https://github.com/BNFC/bnfc/issues/147#issuecomment-117701801>.

**Comment by bezirg** [comment]
That file extracted is the license, not an executable

**Comment by gdetrez** [comment]
Interesting... :confused:

**Comment by gdetrez** [comment]
I found the problem. I changed the script so that it would include the license in the package but I screw up the packaging. It's fixed now. I you're in a hurry you can get the latest successful build at https://ci.zjyto.net/job/BNFC/job/bnfc-pipeline/
Thanks for reporting this!

**Comment by gdetrez** [comment]
OK. I have now uploaded new packages for the 2.8 version. Thanks for reporting this!
