### ISSUE TITLE
How to express optional element in LBNF?

### ISSUE THREAD

**Issue by dorafmon** [BNFC/bnfc#150]
Hi, I just want to know how to express optional element in LBNF? E.g. I have the following rule in ordinary EBNF:
```
LIST_COMMAND =:: "LIST"  [COMMODITY [DELEAR_ID]]
```
How can I express this in LBNF? I used ``[`` and ``]`` and it does not work with bnfc.

**Comment by gdetrez** [comment]
bnfc doesn't support optional elements (yet). So you need to expand your rule, something like:
```
LIST_COMMAND ::= "LIST" Foo ;
Foo ::= ;
Foo ::= COMMODITY Bar ;
Bar ::= ;
Bar ::= DELEAR_ID ;
```

**Comment by gdetrez** [comment]
(related to #65)
