### ISSUE TITLE
String rendering in Java does not work

### ISSUE THREAD

**Issue by gapag** [BNFC/bnfc#159]
BNFC 2.8.
Consider grammar

```
One . BugOne ::= "the_following_is_a_quoted_string" String;
```

run 

```
bnfc --java -m quotebug.cf
make
```

then

```
java quotebug.Test < input
```

where `input` 's content is

```
the_following_is_a_quoted_string "here I am"
```

Output is 

```
Parse Succesful!

[Abstract Syntax]

(One "here I am") 

[Linearized Tree]

the_following_is_a_quoted_string here I am
```

but last line should be

```
the_following_is_a_quoted_string "here I am"
```

**Comment by gdetrez** [comment]
Can you open a PR with your fix?

**Comment by gapag** [comment]
The commit is within the big pull https://github.com/BNFC/bnfc/pull/155, the 4008c8b above
Or do you want me to make another pull request explicitly?

The other commit fe86d45 is on a branch of mine that cannot be merged painlessly...

**Comment by gdetrez** [comment]
Hum, no, I didn't realize it was already merged :-) Does that mean we can close this issue?

**Comment by gapag** [comment]
Tested manually on 843075ef789ba0ef5c85eaa9040a12fddc7950bd with the example above. To be on the safe side, could you add the example above to the regression-tests and then close the issue?
