### ISSUE TITLE
Quoted tokens containing whitespace in .cf file confuse Java backend

### ISSUE THREAD

**Issue by gapag** [BNFC/bnfc#160]
BNFC 2.8.
On input `whitebug.cf`:
```
One . BugOne ::= "white spaces";
```
```
bnfc --java -m whitebug.cf
make
```
JLex returns an error:
```
Creating NFA machine representation.
Error: Parse error at line 27.
```
Using the `--jflex` option seems to go through the Makefile, but inputting a file with proper content gives:
```
java quotebug.Test < spacebug 
At line 1, near "white spac" :
     Error: could not match input
```

Replacing the whitespaces in the quoted token with any nonwhite character in the .cf file seems to prevent this problem.

**Comment by gdetrez** [comment]
Is that the released version or git head?
Since a3a41499a6421ad3f9eb6f5e208760a15632e084, the terminals are split on space characters so `"white spaces"` should be interpreted as `"white" "spaces"`.

**Comment by gapag** [comment]
Released version. It works for the latest build. Sorry for bothering.

**Comment by gdetrez** [comment]
No worries. It reminds me I should probably make a new release...
