### ISSUE TITLE
Skeleton.H has wrongly generated quotes around method name parts and parameters in cpp mode

### ISSUE THREAD

**Issue by dcavar** [BNFC/bnfc#164]
The Skeleton.H is generated wrongly in 2.8 (not so in 2.6a):

  void visit"Integer"("Integer" x);
  void visit"Char"("Char" x);
  void visit"Double"("Double" x);
  void visit"String"("String" x);
  void visit"Ident"("Ident" x);

should be

  void visitInteger(Integer x);
  void visitChar(Char x);
  void visitDouble(Double x);
  void visitString(String x);
  void visitIdent(Ident x);

DC

**Comment by gdetrez** [comment]
Thanks for reporting. I think I fixed this particular problem but uncovered many more in the process :disappointed:
