### ISSUE TITLE
Comments with single-character delimiters not working

### ISSUE THREAD

**Issue by dcavar** [BNFC/bnfc#169]
As we discussed on the list, comments enclosed in quotes:
comment "\"" "\"";
do not work (I am talking about C++). As Aarne Ranta pointed out, "the enclosed comments don't seem to work with any one-character delimiters:
  comment "[" "]" ;
doesn't work either, at least with Haskell/Alex."
Best!
DC

**Comment by andreasabel** [comment]
Single character block comment delimiters have been implemented now in #202.
