### ISSUE TITLE
[Feature Request] SML Backend

### ISSUE THREAD

**Issue by ayberkt** [BNFC/bnfc#178]
It would be nice to have a Standard ML backend. I believe ML-Lex and ML-Yacc are pretty similar to analogous tools for OCaml so it should be easy to implement.

**Comment by gdetrez** [comment]
Hi @ayberkt. Nice that you started working on this. Do not hesitate to ping me if you need any help!

**Comment by andreasabel** [comment]
It seems this issue has been abandoned.  It should not be too hard get an SML backend from an OCaml backend.  Ideally, there would be a more general backend that can be instantiated to both dialects...
