### ISSUE TITLE
Docker build

### ISSUE THREAD

**Issue by kelostrada** [BNFC/bnfc#180]
Hey guys,
I had some issues with compiling bison on OSX therefore I created a Docker build for BNFC, I hope you don't mind. For your information it's here:
https://hub.docker.com/r/kelu/bnfc/

**Comment by gdetrez** [comment]
We surely don't mind ;-) For other OSX user to know about it, you might want to send it to the [mailing list](https://groups.google.com/forum/#!forum/bnfc-dev)
