### ISSUE TITLE
Latest release points to 2.8 instead of 2.8.1

### ISSUE THREAD

**Issue by dschoepe** [BNFC/bnfc#189]
The latest release linked to on the BNFC website and the one designated on github is 2.8 instead of the more recent 2.8.1. Since 2.8 produces Haskell code that no longer compiles with modern versions of GHC, alex, and happy, this makes it necessary for users to discover that 2.8.1 actually fixes this issue.

**Comment by gdetrez** [comment]
Thanks! I created a new release on github for 2.8.1
