### ISSUE TITLE
FYI: Syntax highlighting for Sublime Text

### ISSUE THREAD

**Issue by Centril** [BNFC/bnfc#190]
For your information:

I have created a **syntax highlighting definition** for **sublime text.**
Here it is: **https://github.com/Centril/sublime-lbnf-syntax**

Enjoy =)

**Comment by gdetrez** [comment]
Thanks! I added a link in the docs. You might want to post on the mailing list about this as well.

**Comment by Centril** [comment]
@gdetrez done =) https://groups.google.com/forum/#!topic/bnfc-dev/m1YGxc7SSFk
