### ISSUE TITLE
Missing return value in initialize_lexer

### ISSUE THREAD

**Issue by Teemperor** [BNFC/bnfc#196]
Generating a C++ parser from this grammar[1] produces code that crashes under clang++. The reason is that bnfc it doesn't write a return statement in the initialize_lexer function:

    int initialize_lexer(FILE *inp) { yyrestart(inp); BEGIN YYINITIAL; }

BEGIN is #defined as `#define BEGIN (yy_start) = 1 + 2 *` and YYINITIAL as `#define YYINITIAL 1`.
So there is no return in this function which will result in SIGILL when compiled with clang++ (because it's undefined behavior in C++).

A simple fix for me was to add a simple "return 0;" at the end because the return value is never used in my parser. Looking at the code in bfnc that generates the lexer that doesn't seem like a reuseable fix though.

[1] http://www.cse.chalmers.se/edu/year/2016/course/DAT151_Programming_Language_Technology/laborations/lab2/CPP.cf

**Comment by gdetrez** [comment]
I didn't manage to reproduce this with master. Here is how I tried:
```sh
bnfc CPP.cf -o tmp --cpp -m
make -C tmp CC=clang++ CCFLAGS=''  -B 
```

But it seems that `initialize_lexer` is a bnfc thing (it's not required by flex or bison) in which case we should be able to just change the return type to `void`. Unless you see a problem that I missed with doing that?

**Comment by Teemperor** [comment]
You need to run the parser. My output is:

    teemperor@ftldrive ~/c/p/test> ls
    CPP.cf
    teemperor@ftldrive ~/c/p/test> bnfc -m -cpp CPP.cf 
    65 rules accepted
    writing new file ./Absyn.H
    writing new file ./Absyn.C
    writing new file ./CPP.l
    writing new file ./CPP.y
    writing new file ./Parser.H
    writing new file ./Skeleton.H
    writing new file ./Skeleton.C
    writing new file ./Printer.H
    writing new file ./Printer.C
    writing new file ./Test.C
    writing new file ./Makefile
    teemperor@ftldrive ~/c/p/test> make CC=clang++
    [lots of warnings]
    CPP.l:76:68: warning: control reaches end of non-void function [-Wreturn-type]
    int initialize_lexer(FILE *inp) { yyrestart(inp); BEGIN YYINITIAL; }
    46 warnings generated.
    clang++ -g -W -Wall -c Test.C
    Linking TestCPP...
    clang++ -g -W -Wall Absyn.o Lexer.o Parser.o Printer.o Test.o -o TestCPP
    teemperor@ftldrive ~/c/p/test> ./TestCPP < /dev/null 
    fish: “./TestCPP < /dev/null” terminated by signal SIGILL (Illegal instruction)

**Comment by gdetrez** [comment]
What version of bnfc are you using? It seem that using master, the problem has been fixed. This is what I have in `CPP.l`: 
```c++
void initialize_lexer(FILE *inp) { yyrestart(inp); BEGIN YYINITIAL; } 
```

**Comment by Teemperor** [comment]
I got the bug using the latest release, but I can't reproduce the actual crash in master, so I guess that's fixed.

However, `grep -R "int initialize_lexer"` reveals that the wrong return type is still in CPP.y when using the master branch :

    > grep -R initialize_lexer
    CPP.l:void initialize_lexer(FILE *inp) { yyrestart(inp); BEGIN YYINITIAL; }
    CPP.y:int initialize_lexer(FILE * inp);

**Comment by gdetrez** [comment]
Thanks for looking at it. We should nonetheless make them consistent :+1:

**Comment by andreasabel** [comment]
Couldn't reproduce the problem, but fixed the return type of `initialize_lexer` to be `void` also in the parser.
