### ISSUE TITLE
unrecognized option `--antlr'

### ISSUE THREAD

**Issue by martinschaef** [BNFC/bnfc#205]
On osx, when installing bnfc via cabal, I get:

```
> cabal install happy alex bnfc
> bnfc --version
2.8.1
> export CLASSPATH=$CLASSPATH:./antlr-4.6-complete.jar
>bnfc --java --antlr -m bnfc/ast.bnfc
unrecognized option `--antlr'
```

The help also doesn't mention the antlr option. I can't use cup because our CI barfs when it tries to compile the generated code with `-wall`.

**Comment by andreasabel** [comment]
The development version as an experimental support for ANTLR.  Version 2.8.1 does not have it, afaik.

**Comment by andreasabel** [comment]
2.8.2 has been released now.
