### ISSUE TITLE
Space awareness for operators

### ISSUE THREAD

**Issue by zhaar** [BNFC/bnfc#208]
Hi,

I'm trying to define a grammar for a language that makes use of spaces around identifiers in order to accepts both those strings unambiguously

    lhs > rhs

    lhs> rhs

where the first line is two identifiers with a infix operator in the middle and the second one is a postfix expression (`lhs>`) followed by another identifier.

Similarly with prefix

    lhs . rhs 

    lhs .rhs

Is it possible? if so how and otherwise why?

**Comment by SzymonPajzert** [comment]
Are these identifiers defined beforehand or you want it to be customisable
by user?

**Comment by zhaar** [comment]
defined beforehand

**Comment by SzymonPajzert** [comment]
Sorry for the long reply. Probably you have already solved that but for the sake of competition I'll post my answer.

I don't think it's possible to do purely in BNFC. I'd suggest in this case modify the lexer to not split words on some subset of identifiers. That depends on the backend you use.

**Comment by andrevidela** [comment]
I'm using the Haskell backend. I've started to rewrite the parser with parsec but I haven't made much progress with my rewrite. 
Could you point me to what kind of modification I should do to the generated lexer?I remember that the lexer file was huge and it was very hard to know which part to modify.

**Comment by SzymonPajzert** [comment]
Using Haskell I haven't changed generated lexer but created a wrapper around it. Take a look at the code I wrote some time ago to split an SQL script into a list of commands. 

``` haskell
module Compile.Parse (parse) where

import Grammar.Par (pProgram, myLexer) -- generated by BNFC
import Data.List.Split (splitWhen)

commandDelim :: Tok
commandDelim = let [PT _ token] = myLexer ";" in token

isCommandDelim :: Token -> Bool
isCommandDelim (PT _ token) = token == commandDelim
isCommandDelim _            = False

lexMany ::  String -> [[Token]]
lexMany file = lex file |> -- I like this OCaml operator
  splitWhen isCommandDelim

parseMany :: String -> [Err Program]
parseMany = (map pProgram) . lexMany -- pProgram comes from BNFC as well
```

What it does it applies lexer to the content of the file and then modifies the tokens without modifying lexer itself. As I understand your problem, you could replace every space with some reserved symbol that would be then passed to lexer (problem with default BNFC is that is not whitespace sensitive). After that you could traverse the list of [Token] and coming across any of your predefined operators and looking at the surrounding spaces, you could define what kind of operator is it (prefix, infix, suffix).

**Comment by andreasabel** [comment]
This feature is out of scope for BNFC.
