### ISSUE TITLE
Java backend generates invalid package name

### ISSUE THREAD

**Issue by andreasabel** [BNFC/bnfc#212]
If my input is `my-grammar.cf`, bnfc will create java code with package name `my-grammar` which is not legal.

**Comment by rabbitonweb** [comment]
what would be the right name for the package? `mygrammar` or `my_grammar`? or just forbid the generation of the java code at all?

**Comment by andreasabel** [comment]
Following https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html it seems that snake_case is the convention.
