### ISSUE TITLE
Classname "Doc" causes errors in Haskell parser

### ISSUE THREAD

**Issue by hjorthjort** [BNFC/bnfc#228]
Steps to reproduce:

1. BNFC file (`Prog.cf`)
```
Document. Doc ::= "d"  
```
2. Run `bnfc -m Prog.cf`
3. Run `make`

Output: [make.log](https://github.com/BNFC/bnfc/files/1957682/make.log)

Other class names that causes the same error:
* `Err`
* `ParseFun`

Inspection shows that this is because `PrintProg.hs` defines `type Doc = [ShowS] -> [ShowS]`. Other modules similarly define types, such as `Err` and `ParseFun`. Since the `AbsProg.hs` file is not imported with a qualified import, there is a namespace conflict.
 
Perhaps it would be sensible to either supply a list of reserved class names and report the use of them when generating the frontend files, or use qualified imports to avoid namespace conflicts.

**Comment by andreasabel** [comment]
Indeed, the `Abs` modules should be imported qualified.  If you look in module `BNFC.Backend.Haskell.CFtoPrinter`, https://github.com/BNFC/bnfc/blob/7c9e8591902c806c17cc5617db228e5f3e02a2ad/source/src/BNFC/Backend/Haskell/CFtoPrinter.hs#L46 you can see that the name of the AST module, `absMod`, is only passed to `prologue`.  To get qualified references, it should be passed to all subroutines, preferably as the state of some `Reader` monad to get all subroutines access to the configuration of the printer generation.  All uses of `Show Cat` should then be replaced to produce qualified references to the AST types.

PRs welcome!

**Comment by andreasabel** [comment]
Related issue: #128, solved in commit 65b958fde11994c224e33f2de4171fd099765890.
I am implementing qualified names for the generated printer as well.
