### ISSUE TITLE
Encode optional / Maybe types

### ISSUE THREAD

**Issue by dmjio** [BNFC/bnfc#230]
Was perusing the google group and noticed there is no support for encoding `Maybe` types in an AST. This would really be a nice to have for a grammar I'm modeling. Has there been any progress since this these issues were posted?

- https://groups.google.com/forum/#!searchin/bnfc-dev/Maybe%7Csort:date/bnfc-dev/By1F6GX3GYs/As9_OVQQCxYJ

- https://groups.google.com/forum/#!searchin/bnfc-dev/Maybe%7Csort:relevance/bnfc-dev/_0KH_totlL0/zol1hGjLyDQJ

**Comment by andreasabel** [comment]
Duplicate of #65.
