### ISSUE TITLE
Flex regex patterns are incorrect.

### ISSUE THREAD

**Issue by justinmeiners** [BNFC/bnfc#237]
Set subtraction is translated to the `#` symbol. Flex doesn't seem to work with patterns containing this symbol. According to [this manual](https://westes.github.io/flex/manual/Patterns.html#Patterns) this is invalid syntax.

Code:
https://github.com/BNFC/bnfc/blob/master/source/src/BNFC/Backend/CPP/NoSTL/RegToFlex.hs#L52

**Comment by andreasabel** [comment]
Ah, thanks for reporting.  That explains why my token definition is not working. ;)

**Comment by andreasabel** [comment]
Fixed in PR #238.
