### ISSUE TITLE
C skeleton uses incorrect function names

### ISSUE THREAD

**Issue by justinmeiners** [BNFC/bnfc#239]
The generating code does this:
https://github.com/BNFC/bnfc/blob/master/source/src/BNFC/Backend/C/CFtoCSkel.hs#L85

But, the calling code does this:
https://github.com/BNFC/bnfc/blob/master/source/src/BNFC/Backend/C/CFtoCSkel.hs#L245

These are not the same since the first uses `islower` on the tail. The result is an invalid skeleton.

**Comment by andreasabel** [comment]
Fixed in PR #238.
