### ISSUE TITLE
Publish on stackage

### ISSUE THREAD

**Issue by flip111** [BNFC/bnfc#241]
would be nice if this package were to be published on stackage to have support for stack

**Comment by flip111** [comment]
I guess wait for https://github.com/BNFC/bnfc/issues/198

**Comment by mukeshtiwari** [comment]
It would be nice if we can install it using Stack.

**Comment by andreasabel** [comment]
BNFC 2.8.4 is now in the stackage nightly https://www.stackage.org/package/BNFC

**Comment by andreasabel** [comment]
BNFC is now part of LTS 16.23: https://www.stackage.org/lts-16.23
