### ISSUE TITLE
support GHCJS

### ISSUE THREAD

**Issue by flip111** [BNFC/bnfc#243]
When ghcjs as compiler is supported bnfc can be running on the bnfc website.

**Comment by andreasabel** [comment]
[GHCJS](https://github.com/ghcjs/ghcjs) does not seem as alive as it could/should be.  I do not see sufficient activity on the repo in 2020.

If we were to look into a JS version of BNFC, we should have a clear motivation why it is the thing we should aim for.  After all, BNFC is a compiler and these usually do not run on websites but are invoked from build-tools or makefiles.

I am closing this issue, but of course, further discussions and contributions are always welcome.
