### ISSUE TITLE
cabal: /usr/bin/ar: permission denied

### ISSUE THREAD

**Issue by alexhkurz** [BNFC/bnfc#245]
Hi, I tried to install bnfc on a MacOS 10.13 following

git clone https://github.com/BNFC/bnfc.git
cd bnfc/source
cabal install

upon which I get 

cabal: /usr/bin/ar: permission denied

I tried to find sth about this issue. Mostly posts from 2015 saying that this issue was resolved in newer version of ghc/cabal. So I installed the latest version of the Haskell Platform for Mac OS X, which is 8.4.3. 

But I have still the same problem.

**Comment by andreasabel** [comment]
Very hard to give remote advice on this.
- Have you checked that the `cabal` that is invoked is actually the newest one?  Which version is it?
- Maybe you have installed some things as `sudo` and not files belong to `root` which shouldn't?!  Make sure the whole trees under `.ghc` and `.cabal` belong to you and are user-writable.

I am closing this issue as it is nothing BNFC specific.  Feel free to come back with more information and reopen it, if you wish further discussion.
