### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by nad** [BNFC/bnfc#248]
Perhaps this is not the right place to report this, but I noticed that some links under http://bnfc.digitalgrammars.com/ are broken:
* All download links on the [Download page](http://bnfc.digitalgrammars.com/download/).
* The [download link](http://bnfc.digitalgrammars.com/releases/2018/11/04/download/BNFC-2.8.2.tar.gz) on the [page announcing BNFC 2.8.2](http://bnfc.digitalgrammars.com/releases/2018/11/04/v2.8.2.html).

**Comment by andreasabel** [comment]
Thanks for reporting, the good place to report it would be here:
https://github.com/BNFC/bnfc.github.com/issues/6

The issue should be fixed now.  Can you please verify?

**Comment by nad** [comment]
I checked some of the links, and did not get 404 error messages.
