### ISSUE TITLE
BNFC does not support \r and \f (lexer error)

### ISSUE THREAD

**Issue by andreasabel** [BNFC/bnfc#257]
BNFC chokes on a definition like the following in the grammar file.
```
token Name (char - [ "-(){};.@\" \n\r\t\f" ]) + ;
```
The reason is that the BNF lexer does handle `\r` (carriage return) and `\f` (form feed).

**Comment by jchook** [comment]
Is there a workaround for this until a fix is released?

**Comment by jchook** [comment]
Does anyone know a workaround for this until we can merge a fix?

**Comment by jchook** [comment]
This seems like a critical issue, not an enhancement.

If I cherry-pick your commits, will it fix this issue?

**Comment by andreasabel** [comment]
I now merged my PR.  Let me know if there are problems still.
