### ISSUE TITLE
C++ parser with const char* and not FILE* always returning null

### ISSUE THREAD

**Issue by sorenbug** [BNFC/bnfc#291]
Here's where its being used: https://github.com/hamhub7/nx-TAS/blob/feature/better-scripts/source/script_provider.cpp#L25

I've logged and made sure that `line` is being parsed correctly, and I've tested that `line` against the test binary generated by make and it parses properly.

**Comment by andreasabel** [comment]
Thanks, @sorenbug, for the issue report.  Would you do me the favor and submit a minimized test case consisting of grammar, test program, and test input that demonstrates the behavior you point out here?  Such a test can aid finding the bug and then become part of the regression test suite.

**Comment by sorenbug** [comment]
I'll do my best when I get home in about 10 hours.

**Comment by andreasabel** [comment]
Ping @sorenbug . Would you be able to submit a self-containing example?  Thanks!

**Comment by sorenbug** [comment]
Ah! Sorry! I haven't booted into Linux in a while to work on the project so I totally forgot. I may have time in about 6 hours, I may not. If I do, I'll see about getting right on this. 😅

**Comment by sorenbug** [comment]
I am unable to replicate this on my computer. Parsing works fine.

In fact, I've just discovered that the file I was using to test on my Switch had 3 bytes at the beginning of it for some odd reason: `ef bb bf`. I'm going to fix this and get back to you.

**Comment by sorenbug** [comment]
I can't believe:
1. That was the issue
2. I ran into it so many times while changing up the scripts I was testing

The worst part is that `ef bb bf` is zero-width in most text areas so I wasn't able to tell until I pasted it into CLion.

bruh moment

**Comment by andreasabel** [comment]
Ok, good, so I don't have to worry!
Cheers.
