### ISSUE TITLE
Seemingly incorrect docs for the predefined "Ident" type

### ISSUE THREAD

**Issue by freddyabrahamsson** [BNFC/bnfc#320]
In the docs found at https://bnfc.readthedocs.io/en/latest/lbnf.html#predefined-basic-types the definition for `Ident` is as follows.

> Type `Ident` of identifiers, defined `letter (letter | digit | '_')*`.

According to this definition, the `Ident` type should not match against strings which contain single quotes, such as `x'`, but it does. The real definition should be closer to `letter (letter | digit | '_' | '\'')*`.

**Comment by andreasabel** [comment]
Thanks, this is indeed a mistake in the documentation that I recently introduced in error. This is still correct in v2.8.3 of the documentation: https://bnfc.readthedocs.io/en/v2.8.3/lbnf.html#predefined-basic-types

A fix is on the way.  Thanks for reporting.
