### ISSUE TITLE
Restore Haskell GLR mode

### ISSUE THREAD

**Issue by andreasabel** [BNFC/bnfc#340]
With the hint in https://github.com/simonmar/happy/issues/173#issuecomment-778661448, the `--glr` mode can be tested again.  
- [x] Fix generated `Makefile` to drop `happy` options `--ghc --coerce` when `--glr` is used.
- [x] Add imports needed by GLR-specific code to generated parser `Test`.

**Comment by depsterr** [comment]
Sorry for commenting on this dead issue, but I'm rather confused. The output of bnfc --help (version 2.9.3) states that GLR parsing is deprecated
```
                --glr                   Output Happy GLR parser [deprecated]
```

Yet, this issue is closed. Is GLR parsing supported?

**Comment by andreasabel** [comment]
Sorry for the confusion, @depsterr.  It is still supported, but deprecated, because it is not supported well upstream (by `happy`).  
In the future, the `--glr` option might be removed.  So far, I am supporting it.
