### ISSUE TITLE
Document defined rules in the reference

### ISSUE THREAD

**Issue by shlevy** [BNFC/bnfc#362]
Currently the reference docs make no mention of `define`.

**Comment by andreasabel** [comment]
Ah, when I took over, `define` was still a half-baked feature (see e.g. #266).  I considered removing it, but then it is documented in the [Implementing Programming Languages book](http://www.grammaticalframework.org/ipl-book/).  So instead, I have worked over time to bring all backends up to speed (#285,#287,#338).  
I guess it is time to commit to this feature and include it in the reference manual.

**Comment by andreasabel** [comment]
Blocked by #363.

**Comment by andreasabel** [comment]
#363 is now fixed except for https://github.com/BNFC/bnfc/issues/363#issuecomment-843190433.
