### ISSUE TITLE
Haskell: how to use multiple entrypoints?

### ISSUE THREAD

**Issue by MurakamiKennzo** [BNFC/bnfc#374]
Hi, I just test like this:
```
-- M.cf
EInt.   Exp ::= Integer ;
EType. Type ::= "Int" ;

entrypoints Exp, Type ;
```
complier to Haskell and make:
```shell
$ bnfc -d -m M.cf  
$ make
```

but when I test with the text:
```test.m
Int
```

it outputs as:
```shell
./test.m

Parse              Failed...

Tokens:
1:1	"Int"
syntax error at line 1, column 1 before `Int'
```

and when I changed the order of entrypoints:
```
-- M.cf
EInt.   Exp ::= Integer ;
EType. Type ::= "Int" ;

entrypoints Type, Exp ;
```

it works well, but the Exp not parsed.

so currently the multiple entrypoints isn't support for Haskell?(but the docs said)

Here are some info:
```shell
$ bnfc --version
2.9.2

$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.10.5

$ alex --version
Alex version 3.2.6, (c) 2003 Chris Dornan and Simon Marlow

$ happy --version
Happy Version 1.20.0 Copyright (c) 1993-1996 Andy Gill, Simon Marlow (c) 1997-2005 Simon Marlow
```

**Comment by andreasabel** [comment]
The first non-terminal (aka category) is the default entrypoint that is used by the generated test program.  However, the generated `Par.y` also has the other entrypoints.

If you want to parse either `Exp` or `Type` without knowing which one you get, you need to define a new category and use this as entry point, e.g.:
```
EPExp.  EP ::= Exp;
EPType. EP ::= Type;
```

**Comment by MurakamiKennzo** [comment]
> The first non-terminal (aka category) is the default entrypoint that is used by the generated test program (`Test.hs`). However, the generated `Par.y` also has the other entrypoints.
> 
> If you want to parse either `Exp` or `Type` _without knowing which one you get_, you need to define a new category and use this as entry point, e.g.:
> 
> ```
> EPExp.  EP ::= Exp;
> EPType. EP ::= Type;
> ```

Got it, I find here:
<img width="510" alt="截屏2021-07-30 上午10 44 11" src="https://user-images.githubusercontent.com/28294081/127591997-cf06beab-9f78-4ef3-98af-790d7f148b47.png">
Thanks!
