### ISSUE TITLE
C backend assumes that user of header file includes `stdio.h`

### ISSUE THREAD

**Issue by enedil** [BNFC/bnfc#381]
In the C backend, none of the generated headers include any header from standard library. This is wrong, as `Parser.h` uses `FILE*`, which is defined in `stdio.h`. Thus, `stdio.h` should be also included.

BNFC version that I use: 2.9.1.
OS: Fedora 34
BNFC distribution: `stack`

**Comment by andreasabel** [comment]
Thanks for reporting and the PR, @enedil!  Is this also a problem with the C++ backends?

**Comment by enedil** [comment]
> Thanks for reporting and the PR, @enedil! Is this also a problem with the C++ backends?

It doesn't, since `Parser.H` includes `vector` and `string`, which transitively usually include lots of other standard headers. But that is not guaranteed. I can make this addition as well.

**Comment by andreasabel** [comment]
Thanks @enedil, this is now fixed on `master`.
