### ISSUE TITLE
Build testsuites with GHC 9.4

### ISSUE THREAD

**Issue by andreasabel** [BNFC/bnfc#425]
Blockers for `BNFC`'s tests:
- [x] https://github.com/sol/doctest/pull/375

Blockers for `bnfc-system-tests`:
- [x] https://github.com/maoe/lifted-async/issues/38
  (Succeeds: `cabal build all --allow-newer=async:base --allow-newer=lifted-async:base`)

**Comment by eddiejessup** [comment]
Hi, just letting you know that doctest has a release supporting 9.4 now

**Comment by andreasabel** [comment]
Excellent, thank you!
