### ISSUE TITLE
GHC 9.6

### ISSUE THREAD

**Issue by andreasabel** [BNFC/bnfc#437]
It seems that no new release is needed for GHC 9.6 (builds locally), but our testsuites are blocked on the ecosystem.

`BNFC` doctests:
- [x] blocked on https://github.com/sol/doctest/issues/394

`bnfc-system-tests`:
- [x] blocked on https://github.com/skogsbaer/HTF/issues/118
- [x] blocked on https://github.com/jacobstanley/unix-compat/issues/61

TODOs:
- [x] add `bnfc-system-tests` to CI for 9.6
- [x] reenable doctests in CI, but only for non-head job
- [x] fix caching in stack workflow (busts 10G limit)
- [x] update `stack-9.2.*.yaml` files

**Comment by sol** [comment]
https://github.com/sol/doctest/pull/401 will hit Hackage after CI.
