### ISSUE TITLE
Java serialization (pretty print) of strings does not escape special chars

### ISSUE THREAD

**Issue by marco-comini** [BNFC/bnfc#449]
While predefined basic type `String` in Haskell backend serialization escapes special chars in strings (like `"line1\nline2"`) in Java it does not (and output is `"line1`
`line2"`).

**Comment by andreasabel** [comment]
This issue exists in all non-FP backends.

**Comment by andreasabel** [comment]
While working on this issue, I found that two backends do not lex escape characters in properly:
- #451 
- #452

**Comment by marco-comini** [comment]
thank you
