### ISSUE TITLE
Release support for ghc 9.8.1

### ISSUE THREAD

**Issue by chenrui333** [BNFC/bnfc#469]
I saw there is [a change for supporting ghc 9.8.1](https://github.com/BNFC/bnfc/commit/e0a0fd67bbddcf5d2561668a24d903757fed66a6), can we cut a release for it? Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/153883

**Comment by andreasabel** [comment]
> I saw there is [a change for supporting ghc 9.8.1](https://github.com/BNFC/bnfc/commit/e0a0fd67bbddcf5d2561668a24d903757fed66a6), can we cut a release for it? Thanks!

The Hackage-released BNFC 2.9.5 supports GHC 9.8.1, are there any problems with it?

The commit you point to is just fixes for the CI here.

Also, if you look at the diff between current `master`and `v2.9.5`, there isn't anything of interest (no code change): https://github.com/BNFC/bnfc/compare/v2.9.5...master#files_bucket

Let me know whether this answers your request.

**Comment by chenrui333** [comment]
Interesting, I had some build issue. Let me posted in here with it.

**Comment by chenrui333** [comment]
@andreasabel I see you have updated the CI config for that change, but you actually did not release it, that is why I raised this issue :) 

```
/private/tmp/bnfc-20231122-42886-1plkwdu/bnfc-2.9.5/dist-newstyle/sdist/bnfc-system-tests-2.9.5.0.tar.gz
Warning: Unknown/unsupported 'ghc' version detected (Cabal 3.10.1.0 supports
'ghc' version < 9.8): /opt/homebrew/opt/ghc/bin/ghc is version 9.8.1
Warning: Unknown/unsupported 'ghc' version detected (Cabal 3.10.1.0 supports
'ghc' version < 9.8): /opt/homebrew/opt/ghc/bin/ghc is version 9.8.1
```

**Comment by chenrui333** [comment]
Actually it builds out fine now, just filed [a new PR](https://github.com/Homebrew/homebrew-core/pull/155197) to build/test with ghc 9.8. Let's see how it goes

**Comment by chenrui333** [comment]
Looks like it builds out fine now, closing the issue.
