### ISSUE TITLE
Use white-space as separator

### ISSUE THREAD

**Issue by gdetrez** [BNFC/bnfc#70]
A frequent question is how to use white-space as a separator, doing this: 

```
separator A " ";
```

doesn't work and the answer is to use an empty string:

```
separator A "";
```

Maybe bnfc could accept `" "` as a separator and treat it like `""`.

**Comment by andreasabel** [comment]
It is easy to treat white space `separator` rules as `terminator ""` rules.  (Fixed.)
A bit more work is needed if we want to print the user provided white space separators faithfully. (Done for the Haskell backend, so far.)

**Comment by andreasabel** [comment]
Printing now fixed for the other backends.
