### ISSUE TITLE
[C#] position tokens don't work

### ISSUE THREAD

**Issue by ikeyan** [BNFC/bnfc#99]
in t.cf:

> position token T letter+;
> ...

out dot.l:

> ...
> <YYINITIAL>{alpha}+    if(Trace) System.Console.Error.WriteLine(yytext); yylval.identity_ = new dot.Absyn.Identity(yytext); return (int)Tokens.SYMB_12;
> ...

error msg::

> error CS1729: 't.Absyn.T' does not contain a constructor that takes 1 arguments.

**Comment by andreasabel** [comment]
The C# backend will be removed in BNFC 2.9.
